### ISSUE TITLE
关于电费充值

### ISSUE THREAD

**Issue by KaitoD** [THUInfo/THUInfo#1]
使用THUInfo进行了电费充值后是否需要其余操作？在使用后宿舍的电表始终没有反应。由于涉及到经济问题，希望开发者可以尽快给一个合理解答。

**Comment by THUInfo** [comment]
感谢您的反馈，我们下一版本会增加查看充值记录的功能。
不过现在请按照以下操作先排查一下原因：
- 校园网环境下进入http://myhome.tsinghua.edu.cn/
- 输入学号和密码（这里的密码可能会有些坑，如果无效我们继续保持沟通）
- 进入http://myhome.tsinghua.edu.cn/Netweb_List/netweb_ele_pay_record.aspx
查看自己的充值记录。

唔按照你的描述，应该是支付宝上有记录而充值记录上没有显示……？
如果确实是这样的话回复一下，我领锅，然后我看看能不能解决这个问题。

**Comment by UNIDY2002** [comment]
抱歉并没有很尽快地给出合理答复，现在给一个：
https://github.com/UNIDY2002/THUInfo/issues/35
https://github.com/UNIDY2002/THUInfo/commit/601f0b6d60ebb83faba28f8c201a3cee3cfc29dd
