### ISSUE TITLE
新增功能建议

### ISSUE THREAD

**Issue by Dazhuzhu-github** [THUInfo/THUInfo#3]
1. 建议可以新增游泳馆的预约功能
2. 之前的where my course gone 的功能是否有机会可以并入app功能

**Comment by UNIDY2002** [comment]
1. 我这段时间考察一下可行性
2. 话说where my course gone是什么呀，求普及

**Comment by YiHui-Liu** [comment]
> 1. 我这段时间考察一下可行性
> 2. 话说where my course gone是什么呀，求普及

where my course gone是这个网站的功能：https://wmcgcdn.rika.tech/#/
大概就是通过网络学堂的接口，获取每一门课的上课教室，方便同学蹭课

**Comment by UNIDY2002** [comment]
感谢建议！我们看看如果可行就把它们加上。
